# Simple Test Playbook
- name: Simple Checks
  hosts: azure_servers
  tasks:
    - name: Show Date
      command: date

    - name: Show Hostname
      command: hostname

    - name: Copy Example File
      copy:
        src: test-file.txt
        dest: /tmp/test-file.txt
